plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules: [{"type": "refactor", "release": "patch"}]
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/gitlab"
  - "@semantic-release/npm"
  - - "@semantic-release/exec"
    - prepareCmd: "rm -f .git/hooks/pre-push"
  - - "@semantic-release/git"
    - assets: ["package.json", "package-lock.json"]
      message: "ci(release): ${nextRelease.version}\n\n${nextRelease.notes}"
branches:
  - "prod"
  - name: "master"
    prerelease: "alpha"
